---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism-secret
  namespace: photoprism
spec:
  encryptedData:
    admin-password: AgCbVvRaeAZ0d0g+cAChtNKu6ceuLLA+BTqcWLtlUZgvpHJkjwyIavriIrzxcKpUMZ31b7BuX6wHfDZzScCS2EpAs//cSXlBO33+793IpoM3y8YZNCfgraC59kOhR2ivZ8N69a0Yyh6sjAN0iMcpkKQ7PmZ83rqTxe0Q0yLNH8un/1HKyblKAFASgk/Bgtce9DcaQUUc7AC71XpLb/QHG0sdc+UijMWuMbK/GNsqu33SmPVVK9mpnWWBnClAmxaqw1EDIvmirNbCtR9xWl4KLiXW0CO21FAb1Divd4xZ+ES82mlkK04kBFxywwURLV3df6YVj/9EhnexMKnv22ei2hogxqwuMdNqhcPaZunvaiuz8ZVBeDhl/HAMfKcLIjMPmxpE2F5QliGt7Z5Dbe8GdKwT94mfCoTYh6BvEHsU/M3bzM2aVflWO9P/8HhUqnDM4wC2H5ouKos9yQz0QE/O+T3vJ4xT0x63ir4Uwyc9B+jWgoOFZPZ/Ojth3DN1HLw3+SUsHHBDtXk3DXNO0+yczhkVBefn+OiQlsuhw3CCrFPmBo8NQ2KlZfMgyfe+pu7eK8RYhQ/ukwXQ/xjqaCnPVxY3XinQth9/6twC8HiV9QbvunC6XhQ5rXmHsp5tadxPwktaB0/swp05fh3j3MhvLsZEtAv41ePuvpXZmYeZDzMp8iVYFTwRJQ/CQWJiSnIdqi1bt/wQZ1V2UOEF2w==
  template:
    metadata:
      creationTimestamp: null
      name: photoprism-secret
      namespace: photoprism
