apiVersion: v1
kind: PersistentVolume
metadata:
  name: emulator-roms-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.221
    path: /volume1/roms
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator-roms-pvc
  namespace: emulator
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: emulator-roms-pv
  storageClassName: ""
