apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-photos-pv
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.221
    path: /volume1/photos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  volumeName: immich-photos-pv
  storageClassName: ""
