auto lo
iface lo inet loopback

iface nic0 inet manual

auto vmbr0
iface vmbr0 inet static
	address 192.168.1.10/24
	bridge-ports enx9c69d399ce62
	bridge-stp off
	bridge-fd 0

iface nic1 inet manual


source /etc/network/interfaces.d/*

auto wlp0s20f3
iface wlp0s20f3 inet dhcp
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
